#!/usr/bin/env python3
import os
import sys
import random
import time

# =============================================================================
# CONFIGURATION - Modify these settings as needed
# =============================================================================

# Output directories
LOG_DIR = "logs"                # Where HTCondor logs will go
MACRO_DIR = "exec_macs"       # Where generated macro files will go
OUTPUT_FOLDER = "test"          # Result ROOT files (e.g., /eos/cms/store/...)

# HTCondor Settings
QUEUE = "workday"               # espresso, microcentury, longlunch, workday, tomorrow, testmatch, nextweek
EXECUTABLE = "run_wrapper.sh"   # The bash script that runs the job

#number of threads per job
N_THREADS = 1

# Enable extended output in the simulation
EXTENDED_OUTPUT = True

mu_general_settings = [
    "/DTSim/generator/momentum 1000 GeV",
    "/DTSim/generator/sigmaMomentum 990 GeV", 
    "/DTSim/generator/theta 90 deg",
    "/DTSim/generator/phi 0 deg",
    "/DTSim/generator/sigmaTheta 30 deg",
    "/DTSim/generator/sigmaPhi 45 deg",
]

# Datasets to process
DATASETS = {
    'Muons_wallCrossing_Confinement_wireCut': {
        'events_per_job': 2000,
        'n_jobs': 5,
        'commands': mu_general_settings
    },
    'Muons_wallCrossing_Confinement': {
        'events_per_job': 2000,
        'n_jobs': 5,
        'commands': mu_general_settings + [
            "/DTSim/cellSD/enableWireCut false"
        ]
    },
    'Muons_wallCrossing': {
        'events_per_job': 2000,
        'n_jobs': 5,
        'commands': mu_general_settings + [
            "/DTSim/cellSD/enableWireCut false",
            "/DTSim/cellSD/enableElectrostaticConfinement false"
        ]
    },
    'Muons_noFilter': {
        'events_per_job': 2000,
        'n_jobs': 5,
        'commands': mu_general_settings + [
            "/DTSim/cellSD/enableWireCut false",
            "/DTSim/cellSD/enableElectrostaticConfinement false",
            "/DTSim/cellSD/enableWallCrossing false"
        ]
    },
    # Example of another dataset
    # 'Pions': {
    #     'events_per_job': 500,
    #     'n_jobs': 10,
    #     'commands': [
    #         '/gun/particle pi+',
    #         '/DTSim/generator/momentum 50 GeV', 
    #         ...
    #     ]
    # }
}

# =============================================================================
# FUNCTIONS
# =============================================================================

def create_directories():
    """Create necessary directories if they don't exist."""
    # Create main directories
    for d in [LOG_DIR, MACRO_DIR]:
        if not os.path.exists(d):
            os.makedirs(d)
            print(f"Created directory: {d}")
    
    # Create log subdirectories for each dataset
    for name in DATASETS:
        log_subdir = os.path.join(LOG_DIR, name)
        if not os.path.exists(log_subdir):
            os.makedirs(log_subdir)
            print(f"Created log subdirectory: {log_subdir}")
    
    if not os.path.exists(OUTPUT_FOLDER):
        try:
            os.makedirs(OUTPUT_FOLDER)
            print(f"Created output directory: {OUTPUT_FOLDER}")
        except OSError:
            print(f"Warning: Could not create {OUTPUT_FOLDER}. Make sure you have write permissions.")

def create_wrapper_script():
    """Creates the bash script that runs on the worker node."""
    content = f"""#!/bin/bash
# Wrapper script for HTCondor jobs
# Usage: ./run_wrapper.sh <MACRO_FILE>

MACRO_FILE=$1

echo "Starting Job on $(hostname)"
echo "Date: $(date)"
echo "Macro: $MACRO_FILE"

# 1. Setup Environment
# We assume the script is in the submission directory (shared filesystem)
if [ -f "setup_lcg.sh" ]; then
    source setup_lcg.sh
else
    echo "Error: setup_lcg.sh not found!"
    exit 1
fi

# 2. Run Simulation
# We assume the executable is already compiled in build/exampleDTSim
if [ -f "build/exampleDTSim" ]; then
    ./build/exampleDTSim $MACRO_FILE
else
    echo "Error: Executable build/exampleDTSim not found!"
    echo "Please run ./compileDTsim.sh before submitting jobs."
    exit 1
fi

echo "Job finished at $(date)"
"""
    with open(EXECUTABLE, "w") as f:
        f.write(content)
    os.chmod(EXECUTABLE, 0o755)
    print(f"Created wrapper script: {EXECUTABLE}")

def create_submit_file(job_list_file):
    """Creates the HTCondor submit file."""
    content = f"""# HTCondor submit file generated by submitJobs.py

executable              = {EXECUTABLE}
# The macro file path is passed as an argument to the wrapper
arguments               = $(macro_file)

# Logging - Organized by dataset name
output                  = {LOG_DIR}/$(dataset_name)/$(ClusterId).$(ProcId).out
error                   = {LOG_DIR}/$(dataset_name)/$(ClusterId).$(ProcId).err
log                     = {LOG_DIR}/$(dataset_name)/$(ClusterId).log

# Resources
+JobFlavour             = "{QUEUE}"
request_cpus            = {N_THREADS}

# Environment
getenv                  = True
# requirements            = (OpSysAndVer =?= "CentOS7") || (OpSysAndVer =?= "AlmaLinux9")

# Queue jobs from the list
# We read two variables: the macro file path and the dataset name
queue macro_file, dataset_name from {job_list_file}
"""
    with open("submit.sub", "w") as f:
        f.write(content)
    print("Created HTCondor submit file: submit.sub")

def generate_macros_and_joblist():
    """Generates individual macro files and the list of jobs."""
    job_list_file = "job_list.txt"
    jobs = [] # List of tuples (macro_path, dataset_name)

    print("Generating macros...")
    
    # Seed the random number generator with current time
    random.seed(time.time())

    for name, info in DATASETS.items():
        for i in range(info['n_jobs']):
            # Unique tag for this job
            tag = f"{name}_job{i}"
            macro_filename = f"{MACRO_DIR}/{tag}.mac"
            
            # Generate random seeds (using large range for Geant4)
            seed1 = random.randint(1, 900000000)
            seed2 = random.randint(1, 900000000)

            # Create the macro content
            macro_content = f"""# Auto-generated macro for job {tag}

# 1. Define Aliases
/control/alias nThreads {N_THREADS}
/control/alias sed1 {seed1}
/control/alias sed2 {seed2}
/control/alias outdir {OUTPUT_FOLDER}
/control/alias tag _{tag}

# 2. Execute Setup
/control/execute macros/batch/run_setup.mac

# 3. output extended flag
/DTSim/run/extendedOutput {"true" if EXTENDED_OUTPUT else "false"}

# 3. Custom Commands
"""
            # Add custom commands from the dataset configuration
            for cmd in info.get('commands', []):
                macro_content += f"{cmd}\n"

            # 4. Run
            macro_content += f"\n/run/beamOn {info['events_per_job']}\n"

            with open(macro_filename, "w") as f:
                f.write(macro_content)
            
            # Store both the filename and the dataset name for the submit file
            jobs.append((macro_filename, name))

    # Write the list of macros to be processed by HTCondor
    with open(job_list_file, "w") as f:
        for macro_path, dataset_name in jobs:
            f.write(f"{macro_path} {dataset_name}\n")
            
    print(f"Generated {len(jobs)} job macros and {job_list_file}")
    return job_list_file

# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    create_directories()
    create_wrapper_script()
    job_list = generate_macros_and_joblist()
    create_submit_file(job_list)
    
    ###### sends bjobs ######
    print("\nSubmitting jobs...")
    os.system("condor_submit submit.sub")
    print( "your jobs:\n")
    os.system("condor_q")
