# ==============================================================================
# Detector Configuration
# ==============================================================================
# This macro defines the detector settings (SDs, Magnetic Field, Geometry).
# These commands must be executed BEFORE /run/initialize.

# --- Geometry ---
# Path to the geometry file
/DTSim/detector/setGeometryFile geometry/geometry_concentrator.tg

# --- Sensitive Detectors ---
# Enable/Disable Drift Cell SD
/DTSim/detector/enableDriftSD true

# Enable/Disable Station SD
/DTSim/detector/enableStationSD true

# --- Magnetic Field ---
# Enable/Disable magnetic field
#<------------------------------ disable for fast testing
/DTSim/detector/useBField true

# Set global magnetic field (x y z)
/DTSim/detector/BField/setGlobal 0 0 0 tesla

# Set yoke magnetic field (x y z)
/DTSim/detector/BField/setYoke 0 0 -2.0 tesla