# Macro file for exampleDTSim

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4

# Initialize kernel
/run/initialize

# Open a viewer
/vis/open OGL 600x600-0+0

# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 0. 0.
# Specify zoom value:
/vis/viewer/zoom 1.6
# Specify style (surface or wireframe):
/vis/viewer/set/style wireframe #surface

# Disable auto refresh and quieten vis messages whilst scene and trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry:
/vis/drawVolume

# Set a scale reference
# /vis/scene/add/scale 1 cm
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 10 cm
# Add event ID:
/vis/scene/add/eventID

# Draw smooth trajectories at end of event, showing trajectory points as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)

# Draw hits at end of event:
#/vis/scene/add/hits

# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma

# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true

# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# command for testing
/DTSim/generator/randomizePrimary 0
/DTSim/generator/momentum 200 GeV

/vis/scene/add/magneticField 10

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

# For file-based drivers, use this to create an empty detector view:
/vis/viewer/flush
