# ==============================================================================
# Batch mode execution macro for DTSimulator
# ==============================================================================
# this is a template macro for batch execution
# replace {nThreads}, {outdir}, {tag}, {sed1}, {sed2} with desired values 
# with /control/alias before use

# Load standard settings
/random/setSeeds {sed1} {sed2}
/run/numberOfThreads {nThreads}
/control/execute macros/settings/verbosity_quiet.mac

# Load preInit macros
/control/execute macros/settings/detector.mac
/control/execute macros/settings/limits.mac

# Set the output filename
/DTSim/run/setOutputFileName {outdir}/DTG4Simulation{tag}

# Initialize kernel
/run/Initialize

# Load postInit macros
/control/execute macros/settings/cuts.mac
/control/execute macros/settings/primary.mac
/control/execute macros/settings/physics.mac
